### PR TITLE
Fix pad token id issue for transformers v5 support

### PR DESCRIPTION
**Pull request by vaibhavjindal**
## Summary

Fix multiple failing monkey_patch tests for transformers v5. The tests failed because of https://github.com/huggingface/transformers/pull/41541.

These changes are backward compatible.

This change fixes the following failing tests:
```
FAILED test/transformers/test_monkey_patch.py::test_apply_liger_kernel_to_instance_for_qwen3_vl_moe_for_conditional_generation - AttributeError: 'Qwen3VLMoeTextConfig' object has no attribute 'pad_token_id'
FAILED test/transformers/test_monkey_patch.py::test_apply_liger_kernel_to_instance_for_qwen3_vl_moe - AttributeError: 'Qwen3VLMoeTextConfig' object has no attribute 'pad_token_id'
FAILED test/transformers/test_monkey_patch.py::test_apply_liger_kernel_to_instance_for_qwen3_vl_moe_text - AttributeError: 'Qwen3VLMoeTextConfig' object has no attribute 'pad_token_id'
FAILED test/transformers/test_monkey_patch.py::test_apply_liger_kernel_to_instance_for_llama4_for_conditional_generation - AttributeError: 'Llama4Config' object has no attribute 'pad_token_id'
FAILED test/transformers/test_monkey_patch.py::test_apply_liger_kernel_to_instance_for_glm4v - AttributeError: 'Glm4vTextConfig' object has no attribute 'pad_token_id'
```

Fixes https://github.com/linkedin/Liger-Kernel/issues/1059.

## Testing Done

- Hardware Type: <BLANK>
- [ ] run `make test` to ensure correctness
- [ ] run `make checkstyle` to ensure code style
- [ ] run `make test-convergence` to ensure convergence

### CODE REVIEW

**Comment by vaibhavjindal** [comment]
@Tcc0403 @shimizust @Mecoli1219 for review

**Review by Tcc0403 — APPROVED** [review]
Thanks LGTM

**Comment by vaibhavjindal** [comment]
https://github.com/linkedin/Liger-Kernel/issues/1059
